# Generated by Django 6.1.1 on 2026-09-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
