# Generated by Django 6.1.1 on 2026-09-15 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_country', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('destination_country', models.CharField(max_length=50)),
                ('confirmed_on', models.DateField()),
                ('incentive_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('incentive_paid', models.BooleanField(default=False)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='employees.employee')),
            ],
            options={
                'ordering': ['-confirmed_on'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('leave_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('incentive_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='employees.employee')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
