# Generated by Django 6.1.1 on 2026-09-16 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_dailyattendance'),
        ('employees', '0004_remove_employee_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyattendance',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Daily attendance'},
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('leave', 'Leave'), ('absent', 'Absent'), ('needs_review', 'Needs Review'), ('holiday', 'Holiday')], default='present', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='dailyattendance',
            unique_together={('employee', 'date')},
        ),
    ]
